### ISSUE TITLE
Multiple transforms?

### ISSUE THREAD

**Issue by gotson** [ddimtirov/gwo-agent#1]
Hi, is it possible to perform multiple transforms ?

For instance i would like to:

- proxify downloads through our internal Nexus mirror
- force the download of type `all` even if `bin` is specified

**Comment by ddimtirov** [comment]
Yes, you can. Look for the [Advanced Usage](https://github.com/ddimtirov/gwo-agent#advanced-usage) section of the readme. Let me know if the examples are not clear.

**Comment by gotson** [comment]
Thanks, after a brush-up session on `sed`'s replace format i got it working!
